{% set version = '0.8.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-citation
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/citation_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/citation/citation_{{ version }}.tar.gz
  sha256: 6f90fab48f16f404b338271948add77bf960d312d4e54b2ed55789a35cd7d068

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-desc
    - r-jsonlite
    - r-withr
    - r-yaml
  run:
    - r-base
    - r-desc
    - r-jsonlite
    - r-withr
    - r-yaml

test:
  commands:
    - $R -e "library('citation')"           # [not win]
    - "\"%R%\" -e \"library('citation')\""  # [win]

about:
  home: https://github.com/pik-piam/citation
  license: BSD-2-Clause
  summary: A collection of functions to extract citation information from 'R' packages and to
    deal with files in 'citation file format' (<https://citation-file-format.github.io/>),
    extending the functionality already provided by the citation() function in the 'utils'
    package.
  license_family: BSD
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_2_clause'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: citation
# Type: Package
# Title: Software Citation Tools
# Version: 0.8.2
# Date: 2023-03-30
# Authors@R: c( person("Jan Philipp", "Dietrich", email = "dietrich@pik-potsdam.de", role = c("aut","cre")), person("Waldir", "Leoncio", email = "w.l.netto@medisin.uio.no", role = c("aut")))
# Description: A collection of functions to extract citation information from 'R' packages and to deal with files in 'citation file format' (<https://citation-file-format.github.io/>), extending the functionality already provided by the citation() function in the 'utils' package.
# Imports: desc, jsonlite, utils, withr, yaml
# Suggests: covr, testthat
# URL: https://github.com/pik-piam/citation, https://doi.org/10.5281/zenodo.3813429
# BugReports: https://github.com/pik-piam/citation/issues
# License: BSD_2_clause + file LICENSE
# Encoding: UTF-8
# RoxygenNote: 7.2.3
# NeedsCompilation: no
# Packaged: 2023-03-30 18:07:46 UTC; dietrich
# Author: Jan Philipp Dietrich [aut, cre], Waldir Leoncio [aut]
# Maintainer: Jan Philipp Dietrich <dietrich@pik-potsdam.de>
# Repository: CRAN
# Date/Publication: 2023-03-30 18:30:02 UTC
